expected_output = {
    "Atm0/0/0": {
        "enabled": True,
        "line_status": True,
        "line_up_since": "2022-01-20 17:52:13 UTC+01:00",
        "interface_description": "Connection to IP-VPN # ax10001b #",
        "mtu": 1500,
        "time_last_up": "2022-01-20 17:52:13 UTC+01:00",
        "system_time": "2022-01-27 16:24:34+01:00",
        "input_rate_bits": "424",
        "input_rate_packets": "0",
        "output_rate_bits": "248",
        "output_rate_packets": "0",
        "input_packets": "159078",
        "input_bytes": "16881401",
        "output_packets": "60908",
        "output_bytes": "6664962"
    },
    "Cellular0/0/0": {
        "cellular_info": {
            "modem_state": "Present",
            "modem_model": "ME909s-120",
            "wireless_technology": "Unknown",
            "rssi": "Unknown"
        },
        "enabled": False,
        "line_status": False,
        "interface_description": "HUAWEI, AR Series, Cellular0/0/0 Interface",
        "mtu": 1500,
        "time_last_up": "-",
        "system_time": "2022-01-27 16:24:34+01:00",
        "input_packets": "0",
        "input_bytes": "0",
        "output_packets": "0",
        "output_bytes": "0"
    },
    "Cellular0/0/1": {
        "cellular_info": {
            "modem_state": "Not present"
        },
        "enabled": False,
        "line_status": False,
        "interface_description": "HUAWEI, AR Series, Cellular0/0/1 Interface",
        "mtu": 1500,
        "time_last_up": "-",
        "system_time": "2022-01-27 16:24:35+01:00",
        "input_packets": "0",
        "input_bytes": "0",
        "output_packets": "0",
        "output_bytes": "0"
    },
    "GigabitEthernet0/0/0": {
        "enabled": False,
        "line_status": False,
        "interface_description": "HUAWEI, AR Series, GigabitEthernet0/0/0 Interface",
        "time_last_up": "-",
        "system_time": "2022-01-27 16:24:35+01:00",
        "port_mode": "COMMON COPPER",
        "port_speed": "FULL",
        "port_negotiation": "ENABLE",
        "input_rate_bits": "0",
        "input_rate_packets": "0",
        "output_rate_bits": "0",
        "output_rate_packets": "0",
        "input_packets": "0",
        "input_bytes": "0",
        "output_packets": "0",
        "output_bytes": "0"
    },
    "GigabitEthernet0/0/1": {
        "enabled": False,
        "line_status": False,
        "interface_description": "HUAWEI, AR Series, GigabitEthernet0/0/1 Interface",
        "time_last_up": "-",
        "system_time": "2022-01-27 16:24:35+01:00",
        "port_mode": "COMMON COPPER",
        "port_speed": "FULL",
        "port_negotiation": "ENABLE",
        "input_rate_bits": "0",
        "input_rate_packets": "0",
        "output_rate_bits": "0",
        "output_rate_packets": "0",
        "input_packets": "0",
        "input_bytes": "0",
        "output_packets": "0",
        "output_bytes": "0"
    },
    "GigabitEthernet0/0/2": {
        "enabled": False,
        "line_status": False,
        "interface_description": "HUAWEI, AR Series, GigabitEthernet0/0/2 Interface",
        "time_last_up": "-",
        "system_time": "2022-01-27 16:24:36+01:00",
        "port_mode": "COMMON COPPER",
        "port_speed": "FULL",
        "port_negotiation": "ENABLE",
        "input_rate_bits": "0",
        "input_rate_packets": "0",
        "output_rate_bits": "0",
        "output_rate_packets": "0",
        "input_packets": "0",
        "input_bytes": "0",
        "output_packets": "0",
        "output_bytes": "0"
    },
    "GigabitEthernet0/0/3": {
        "enabled": False,
        "line_status": False,
        "interface_description": "HUAWEI, AR Series, GigabitEthernet0/0/3 Interface",
        "time_last_up": "-",
        "system_time": "2022-01-27 16:24:36+01:00",
        "port_mode": "COMMON COPPER",
        "port_speed": "FULL",
        "port_negotiation": "ENABLE",
        "input_rate_bits": "0",
        "input_rate_packets": "0",
        "output_rate_bits": "0",
        "output_rate_packets": "0",
        "input_packets": "0",
        "input_bytes": "0",
        "output_packets": "0",
        "output_bytes": "0"
    },
    "GigabitEthernet0/0/4": {
        "enabled": False,
        "line_status": False,
        "interface_description": "HUAWEI, AR Series, GigabitEthernet0/0/4 Interface",
        "mtu": 1500,
        "time_last_up": "-",
        "system_time": "2022-01-27 16:24:37+01:00",
        "port_mode": "COMMON COPPER",
        "port_speed": "FULL",
        "port_negotiation": "ENABLE",
        "input_rate_bits": "0",
        "input_rate_packets": "0",
        "output_rate_bits": "0",
        "output_rate_packets": "0",
        "input_packets": "0",
        "input_bytes": "0",
        "output_packets": "0",
        "output_bytes": "0"
    },
    "GigabitEthernet0/0/5": {
        "enabled": False,
        "line_status": False,
        "interface_description": "VirtualPort",
        "mtu": 1500,
        "time_last_up": "-",
        "system_time": "2022-01-27 16:24:38+01:00",
        "port_mode": "COMMON COPPER",
        "port_speed": "FULL",
        "port_negotiation": "ENABLE",
        "input_rate_bits": "0",
        "input_rate_packets": "0",
        "output_rate_bits": "0",
        "output_rate_packets": "0",
        "input_packets": "0",
        "input_bytes": "0",
        "output_packets": "0",
        "output_bytes": "0"
    },
    "LoopBack0": {
        "enabled": True,
        "interface_description": "HUAWEI, AR Series, LoopBack0 Interface",
        "mtu": 1500,
        "ip_address": "10.1.1.138",
        "subnet_prefix": "32",
        "subnet_mask": "255.255.255.255",
        "system_time": "2022-01-27 16:24:38+01:00",
        "input_rate_bits": "0",
        "input_rate_packets": "0",
        "output_rate_bits": "0",
        "output_rate_packets": "0"
    },
    "NULL0": {
        "enabled": True,
        "interface_description": "HUAWEI, AR Series, NULL0 Interface",
        "mtu": 1500,
        "system_time": "2022-01-27 16:24:38+01:00",
        "input_rate_bits": "0",
        "input_rate_packets": "0",
        "output_rate_bits": "0",
        "output_rate_packets": "0"
    },
    "Virtual-Template0": {
        "enabled": True,
        "line_status": True,
        "line_up_since": "2022-01-20 17:52:14 UTC+01:00",
        "interface_description": "HUAWEI, AR Series, Virtual-Template0 Interface",
        "mtu": 1500,
        "system_time": "2022-01-27 16:24:39+01:00",
        "input_rate_bits": "160",
        "input_rate_packets": "0",
        "output_rate_bits": "8",
        "output_rate_packets": "0"
    },
    "Vlanif1": {
        "enabled": False,
        "line_status": False,
        "interface_description": "HUAWEI, AR Series, Vlanif1 Interface",
        "mtu": 1500,
        "system_time": "2022-01-27 16:24:39+01:00"
    }
}
